name: flutter_maps
description: A Flutter project for KulinerHunt mapping demo.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Networking
  http: ^1.2.0

  # Map & Location
  flutter_map: ^7.0.0
  latlong2: ^0.9.1
  geolocator: ^13.0.0

  # UI Essentials
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1

  # State management (opsional tapi direkomendasikan)
  provider: ^6.1.2

  # Animations (opsional)
  flutter_animate: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/icons/restaurant.svg
    - assets/icons/pin.svg
    - assets/data/
    - assets/images/
    